### ISSUE TITLE
Добавление на википедию

### ISSUE THREAD

**Issue by kewldan** [maximal/http-267#10]
Ждем одобрения [статьи](https://ru.wikipedia.org/w/index.php?title=%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2_%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F_HTTP&oldid=136859481)

**Comment by kewldan** [comment]
Не одобрена

**Comment by maximal** [comment]
Эх :-(
